# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cosmos
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "/my-blog" # the subpath of your site, e.g. /blog
url: "https://sendtodilip.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Fields minima uses, but are not defaulted with the jekyll new command
# Auther is the default for post, the atom free, and is used in the footer.
auther: Bill Raymond
linkedin_username: williamraymond
youtube_username: ProjectnationBill

# New fields not defaulted by jekyll-new with the ninima theme
# Add a copyright. A copyrigh tsymbol and year will be added automatically
# copyright: Company Name, Inc.
copyright: "Cosmos LLC"

# title-logo is anew field that, when used, displayes alogo
# instead of custom text, ideally, image is 50px high and take up 
# minimal horizonal space, Tested witha new root "images" folder e.g.: 
# title-log: /images/my-logo.png (or JPG, etc.)
title-logo: /images/title_logo.png

# only get the first sentence for the excerpt
# excerpt_separator: .

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
